### ISSUE TITLE
multi-line string literals

### ISSUE THREAD

**Issue by ttilley** [docopt/docopt.swift#4]
Now that swift is open source, we can not only propose features but implement them. Multi-line string literals would make use of docopt significantly less painful in swift. If you share my opinion please vote for this improvement request, and the upcoming swift-evolution proposal: https://bugs.swift.org/browse/SR-170

**Comment by ttilley** [comment]
My initial email to swift-evolution is here: https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20151207/001565.html

Please provide any feedback you might have there.

Note that this isn't a proposal yet. It has to be hashed out via discussion and then made into a proper proposal via the swift-evolution guidelines: https://github.com/apple/swift-evolution/blob/master/process.md

**Comment by kovpas** [comment]
@ttilley thanks for the initiative. I absolutely love it! For docopt.swift it would be really useful. I've read the email thread, looks interesting. Will think more about this and provide my feedback if I have any.

Thanks again!

**Comment by ttilley** [comment]
multi-line string literals **finally** exist in swift 4: https://github.com/apple/swift-evolution/blob/master/proposals/0168-multi-line-string-literals.md

**Comment by kovpas** [comment]
These are awesome news @ttilley! Thanks a lot for your involvement in this!

**Comment by kovpas** [comment]
Almost two years passed, and we can finally resolve the issue 🎉

Thanks a lot @ttilley!
